server:
  port: 8080

spring:
  application:
    name: library-manager

  profiles:
    active: postgres

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.schema: debug
    org.springframework.orm.jpa: debug
